# Generated by Django 4.0 on 2022-11-21 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre de la Universidad')),
                ('ubication', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripción')),
                ('oficial_page', models.CharField(max_length=255, verbose_name='Link de la Página Oficial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'db_table': 'universidades',
            },
        ),
    ]
