# Generated by Django 4.0 on 2022-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Carrera')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripción')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Fecha Publicado')),
                ('oficial_page', models.CharField(max_length=255, verbose_name='Link de la Página Oficial de la Carrera')),
                ('pensum_link', models.CharField(max_length=255, verbose_name='Link del Plan de Estudios/Pensum')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'carreras_universitarias',
            },
        ),
    ]
