version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_DB=eduaction_match
      - POSTGRES_USER=hiram
      - POSTGRES_PASSWORD=hackademy
    ports:
      - 5432:5432
    volumes:
      - ~/users_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DEFAULT_PORT=80
    ports:
      - "5050:80"


