# Generated by Django 4.0 on 2022-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Beca')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripción')),
                ('requirements', models.TextField(max_length=800, verbose_name='Requisitos')),
                ('vacancy_numbers', models.IntegerField(default=0, verbose_name='Plazas/Vacantes')),
                ('official_page', models.CharField(max_length=255, verbose_name='URL de la Página de la Beca')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Publicación')),
                ('expiration_date', models.DateField(auto_now_add=True, verbose_name='Vigencia')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
                'db_table': 'becas',
            },
        ),
    ]
