# Generated by Django 4.0 on 2022-11-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Programa')),
                ('description', models.TextField(max_length=1200, verbose_name='Descripción')),
                ('url_program', models.CharField(max_length=255, verbose_name='URL/Link del Programa')),
                ('posted_date', models.DateField(auto_now_add=True, verbose_name='Fecha Publicado')),
                ('expiration_date', models.DateField(auto_now_add=True, verbose_name='Vigencia')),
                ('method', models.TextField(max_length=1200, verbose_name='Metodología')),
                ('objectives', models.TextField(max_length=1200, verbose_name='Objetivos')),
                ('mode', models.CharField(choices=[('P', 'Presencial'), ('V', 'Virtual')], default='P', max_length=1, verbose_name='Modalidad del Programa')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Programas',
                'db_table': 'programas',
            },
        ),
    ]
